USE DW

SELECT
	
	D_DOCENTE.NOME,
	SUM(F_DESEMPENHO.QTD_PAH_PREVISTA) AS TOTAL_PAH_PREVISTA,
	SUM(F_DESEMPENHO.QTD_PAH_REALIZADA) AS TOTAL_PAH_REALIZADA,
	(SUM(F_DESEMPENHO.QTD_PAH_PREVISTA) / SUM(F_DESEMPENHO.QTD_PAH_REALIZADA))*10 AS PAH_REALIZADA_PERC

FROM F_DESEMPENHO
	INNER JOIN D_DOCENTE
		ON D_DOCENTE.SK_DOCENTE = F_DESEMPENHO.SK_DOCENTE

WHERE CPF = '33098663863'
OR 1=1

GROUP BY 
	D_DOCENTE.CPF,
	D_DOCENTE.NOME


--TOTAL_PAH_PREVISTA	TOTAL_PAH_REALIZADA
--11.109.378	12.574.968